name: CI

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install pytest

      - name: Lancer les tests
        id: tests
        run: pytest -v

      - name: SUCCÈS - Fast-forward main sur dev
        if: success()
        run: |
          git config user.email "ci-bot@github.com"
          git config user.name "CI Bot"
          git fetch origin
          git checkout main
          git reset --hard dev
          git push --force origin main

      - name: ÉCHEC - Déplacer le commit sur failures/
        if: failure()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          UNIQUE_ID=$(date +%s)
          git checkout -b failures/$UNIQUE_ID
          git push origin failures/$UNIQUE_ID
          git checkout dev
          git reset --hard HEAD~1
          git push origin dev --force